spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

server.forward-headers-strategy=framework
